gloss_avg = "**Batting Average**  \n=H/AB"
gloss_bat = "**Batting Run Value**  \nCompared to the team average given an equal amount of plate appearances.  \nAlso referred to as Weighted Runs Above Average (wRAA)."
gloss_def = "**Defensive Run Value** Compared to the team average given an equal amount of defensive innings played.  \nAlso includes DH Adjustment."
gloss_g = "**Games Played**"
gloss_hr = "**Home Runs**  \nIncludes both over-the-fence and inside-the-park home runs"
gloss_obp = "**On-Base Percentage**  \n=(H+BB)/PA"
gloss_ops = "**On-Base Plus Slugging**  \n=OBP+SLG"
gloss_pa = "**Plate Appearances**"
gloss_r = "**Runs Scored**"
gloss_rbi = "**Runs Batted In**"
gloss_slg = "**Slugging Percentage**  \n=TB/AB"
gloss_war = "**Wins Above Replacement**  \nAn estimation of wins contributed to the team."
gloss_wrc_plus = "**Adjusted wRC+**  \nWeighted runs created per plate appearance where 100 is team-average, higher is better."
