gloss_1b = "**Singles**"
gloss_2b = "**Doubles**"
gloss_3b = "**Triples**"
gloss_ab = "**At Bats**  \n=PA-BB-SF"
gloss_avg = "**Batting Average**  \n=H/AB"
gloss_babip = "**Batting Average on Balls in Play**  \n=(H-HR)/(AB-SO-HR+SF)"
gloss_bat = "**Batting Run Value**  \nCompared to the team average given an equal amount of plate appearances.  \nAlso referred to as Weighted Runs Above Average (wRAA)."
gloss_bb = "**Bases on Balls / Walks**"
gloss_bb_pct = "**Base on Balls / Walk Percentage**  \nPercentage of all plate appearances ending in a Base on Balls.  \n=BB/PA"
gloss_def = "**Defensive Run Value**  \nCompared to the team average given an equal amount of defensive innings played.  \nAlso includes DH Adjustment."
gloss_g = "**Games Played**"
gloss_h = "**Hits**"
gloss_hidp = "**Double Plays Hit Into**  \nBatted balls that result in two or more outs made by the defense."
gloss_hitp = "**Triple Plays Hit Into**  \nBatted balls that result in three outs made by the defense"
gloss_hr = "**Home Runs**  \nIncludes both over-the-fence and inside-the-park home runs"
gloss_iso = "**Isolated Power**  \n=SLG-AVG"
gloss_k_pct = "**Strikeout Percentage**  \nPercentage of all plate appearances ending in a Strikeout.  \n=SO/PA"
gloss_obp = "**On-Base Percentage**  \n=(H+BB)/PA"
gloss_ops = "**On-Base Plus Slugging**  \n=OBP+SLG"
gloss_ops_plus = "**Adjusted OPS+**  \nOn-Base and Slugging Percentages adjusted where 100 is team-average, higher is better.  \n100*(OBP/teamOBP+SLG/teamSLG-1)"
gloss_pa = "**Plate Appearances**"
gloss_r = "**Runs Scored**"
gloss_rbi = "**Runs Batted In**"
gloss_sf = "**Sacrifice Flies**  \nFly-ball outs that result in at least one run scored."
gloss_slg = "**Slugging Percentage**  \n=TB/AB"
gloss_so = "**Strikeouts**  \nIncludes foul ball outs."
gloss_tb = "**Total Bases**  \n=1B+2x2B+3x3B+4xHR"
gloss_war = "**Wins Above Replacement**  \nAn estimation of wins contributed to the team."
gloss_woba = "**Weighted On-Base Average**  \nA measure of a player's batting contributions, weighted in proportion to each event's actual run value."
gloss_wraa = "**Weighted Runs Above Average**  \nNumber of runs better or worse than the team average given an equal amount of plate appearances."
gloss_wrc = "**Weighted Runs Created**  \nRuns created based on wOBA."
gloss_wrc_plus = "**Adjusted wRC+**  \nWeighted Runs Created per Plate Appearance adjusted where 100 is team-average, higher is better."
gloss_xbh_pct = "**Extra-Base Hit Percentage**  \nPercentage of all plate appearances ending in an Extra-Base Hit.  \n=(2B+3B+HR)/PA"
