SUPABASE_URL = "https://feejfarwgsyfjfxyyaxo.supabase.co"
SUPABASE_KEY = "sb_publishable_3X0TXfRDorbh_wKVUOEzTg_OXbC2Bqz"
CALENDAR_URL = "https://www.quickscores.com/Orgs/DownloadICAL.php?OrgDir=ahpd&LeagueID=1706636&TeamID=14964146&TimeZone=CDT"
